# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: '3.x'
      includePreviewVersions: true

  - script: dotnet restore
    displayName: 'Restore NuGet Packages'

  - script: dotnet build --configuration Release
    displayName: 'Build Project'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/bin/Release/netcoreapp3.1'
      artifactName: 'drop'