# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - '*'

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: 'templates/dotnet-core.yml@templates' # Use a template file for .NET Core
    parameters:
      solution: '**/*.sln'
      buildPlatform: 'windows'
      buildConfiguration: 'Release'
